version: "3.9"

name: "inspirer-applications"

services:
  # ----------------------
  # Microservices section.
  # ----------------------
  
  identity.api:
    container_name: "identity-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis:6379
      - ConnectionStrings__AppDatabase=Server=identity.database;Port=5432;Database=identity;Uid=inspirer;Pwd=1;
    ports:
      - "5050:8080"
    depends_on:
      identity.database:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy # Start Identity API when RabbitMQ is available.
  
  identity.database:
    container_name: "identity-database"
    environment:
      - POSTGRES_USER=inspirer
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=identity
    ports:
      - "5432:5432"
    volumes:
      - identity_database:/var/lib/postgresql/data/
    restart: unless-stopped
    
  
  # ----------------------------
  # Additional services section.
  # ----------------------------
  
  rabbitmq:
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ] # Add a health check to know when service is available.
      interval: 5s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  redis:
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: unless-stopped
    
volumes:
  identity_database:
  
  rabbitmq:
  redis: