version: "3.9"

name: "inspirer-applications"

services:
  # ----------------------
  # Microservices section.
  # ----------------------
  
  identity.api:
    container_name: "inspirer-identity-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis:6379
    ports:
      - "5050:8080"
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy # Start Identity API when RabbitMQ is available.
  
  # ----------------------------
  # Additional services section.
  # ----------------------------
  
  rabbitmq:
    container_name: "inspirer-rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ] # Add a health check to know when service is available.
      interval: 5s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  redis:
    container_name: "inspirer-redis"
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: unless-stopped

  postgres:
    container_name: "inspirer-postgres"
    environment:
      POSTGRES_USER: inspirer
      POSTGRES_PASSWORD: 1
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    
volumes:
  rabbitmq:
  redis:
  postgres: