version: "3.9"

services:
  
  identity.api:
    image: ${DOCKER_REGISTRY-}identity.api
    build:
      context: ../
      dockerfile: src/server/services/Identity/Identity.Api/Dockerfile
      
  identity.database:
    image: "postgres"

  rabbitmq:
    image: "rabbitmq:3-management"
    
  redis:
    image: "redis:alpine"