version: "3.9"

name: "inspirer"

services:

  # Rabbit MQ message bus.
  rabbitmq:
    container_name: "inspirer-rabbitmq"
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    restart: unless-stopped

volumes:
  rabbitmq: